version: "3"

services:
  webserver:
#    build:
#      args:
#        UID: ${SERVER_UID}
#        USER: ${SERVER_USER}
#        GID: ${SERVER_GID}
#        GROUP: ${SERVER_GROUP}
#      context: docker/nginx
    image: altimofeev/webserver-localhost
    container_name: webserver
    working_dir: ${WORKDIR}
    ports:
    - 80:80
    depends_on:
      - app
    volumes:
      - ./code:${WORKDIR}
      - sock:${SOCKET_DIR}

  app:
#    build:
#      args:
#        UID: ${SERVER_UID}
#        USER: ${SERVER_USER}
#        GID: ${SERVER_GID}
#        GROUP: ${SERVER_GROUP}
#      context: docker/fpm
    image: altimofeev/php-fpm-amqp
    container_name: app
    env_file:
      - .env
    working_dir: ${WORKDIR}
    volumes:
      - ./code:${WORKDIR}
      - sock:${SOCKET_DIR}

  db:
    image: postgres:13.2-alpine
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: ${RABBIT_HOST}
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
    - 5672:5672
    - 8081:15672

  mailcatcher:
    container_name: mailcatcher
    hostname: mailcatcher
    image: jeanberu/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  sock:



